spring.application.name=ticketpass-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/ticketpass
spring.datasource.username=ticketpass
spring.datasource.password=ticketpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

ticketmaster.api-key=${TICKETMASTER_API_KEY}
ticketmaster.base-url=https://app.ticketmaster.com/discovery/v2

spring.config.import=optional:file:../.env[.properties]